apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-worker-enhanced
  namespace: temporal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workflow-worker-enhanced
      version: enhanced
  template:
    metadata:
      labels:
        app: workflow-worker-enhanced
        version: enhanced
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: worker
        # Using the local image for now, will update when pushed to ghcr.io/quantumlayer-dev
        image: workflow-worker:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TEMPORAL_HOST
          value: "temporal-frontend:7233"
        - name: LOG_LEVEL
          value: "info"
        - name: WORKER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: QUANTUM_DROPS_URL
          value: "http://quantum-drops.quantumlayer.svc.cluster.local:8090"
        - name: PARSER_SERVICE_URL
          value: "http://parser-service.quantumlayer.svc.cluster.local:8082"
        - name: PREVIEW_SERVICE_URL  
          value: "http://preview-service.quantumlayer.svc.cluster.local:3000"
        - name: SANDBOX_EXECUTOR_URL
          value: "http://sandbox-executor.quantumlayer.svc.cluster.local:8084"
        - name: CAPSULE_BUILDER_URL
          value: "http://capsule-builder.quantumlayer.svc.cluster.local:8086"
        - name: LLM_ROUTER_URL
          value: "http://llm-router.quantumlayer.svc.cluster.local:8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep worker || exit 1"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep worker || exit 1"
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-worker-enhanced
  namespace: temporal
spec:
  selector:
    app: workflow-worker-enhanced
  ports:
  - port: 7233
    targetPort: 7233
    name: grpc
  type: ClusterIP