apiVersion: v1
kind: Namespace
metadata:
  name: quantumlayer
---
apiVersion: v1
kind: Namespace
metadata:
  name: quantumlayer-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-manager
  namespace: quantumlayer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-manager
rules:
- apiGroups: [""]
  resources: ["namespaces", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployment-manager
subjects:
- kind: ServiceAccount
  name: deployment-manager
  namespace: quantumlayer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-manager
  namespace: quantumlayer
  labels:
    app: deployment-manager
    component: orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-manager
  template:
    metadata:
      labels:
        app: deployment-manager
    spec:
      serviceAccountName: deployment-manager
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: deployment-manager
        image: ghcr.io/quantumlayer-dev/deployment-manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8087
          name: http
        env:
        - name: PORT
          value: "8087"
        - name: DEPLOYMENT_NAMESPACE
          value: "quantumlayer-apps"
        - name: BASE_URL
          value: "apps.quantumlayer.io"
        - name: GIN_MODE
          value: "release"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-manager
  namespace: quantumlayer
  labels:
    app: deployment-manager
spec:
  type: NodePort
  ports:
  - port: 8087
    targetPort: 8087
    nodePort: 30887
    name: http
  selector:
    app: deployment-manager
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: deployment-manager-pdb
  namespace: quantumlayer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: deployment-manager