apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-orchestrator-config
  namespace: quantumlayer
data:
  PORT: "8083"
  REDIS_URL: "redis://redis:6379"
  MAX_AGENTS: "10"
  MAX_TASKS_PER_AGENT: "5"
  LOG_LEVEL: "info"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-orchestrator
  namespace: quantumlayer
  labels:
    app: agent-orchestrator
    component: core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-orchestrator
  template:
    metadata:
      labels:
        app: agent-orchestrator
        component: core
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: agent-orchestrator
        image: ghcr.io/quantumlayer-dev/agent-orchestrator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
          name: http
        envFrom:
        - configMapRef:
            name: agent-orchestrator-config
        - secretRef:
            name: llm-credentials
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: agent-orchestrator
  namespace: quantumlayer
  labels:
    app: agent-orchestrator
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: agent-orchestrator
---
apiVersion: v1
kind: Service
metadata:
  name: agent-orchestrator-nodeport
  namespace: quantumlayer
  labels:
    app: agent-orchestrator
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30883
    protocol: TCP
    name: http
  selector:
    app: agent-orchestrator
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-orchestrator-hpa
  namespace: quantumlayer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agent-orchestrator
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80