apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-docs
  namespace: quantumlayer
  labels:
    app: api-docs
    component: documentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-docs
  template:
    metadata:
      labels:
        app: api-docs
        component: documentation
    spec:
      containers:
      - name: api-docs
        image: ghcr.io/quantumlayer-dev/api-docs:ai-native-v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
          name: http
        env:
        - name: PORT
          value: "8090"
        - name: GIN_MODE
          value: "release"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: api-docs
  namespace: quantumlayer
  labels:
    app: api-docs
spec:
  type: ClusterIP
  selector:
    app: api-docs
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: api-docs-nodeport
  namespace: quantumlayer
  labels:
    app: api-docs
spec:
  type: NodePort
  selector:
    app: api-docs
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30890
    protocol: TCP
    name: http