apiVersion: v1
kind: Namespace
metadata:
  name: security-services

---
apiVersion: v1
kind: Service
metadata:
  name: cve-tracker
  namespace: security-services
spec:
  type: ClusterIP
  selector:
    app: cve-tracker
  ports:
  - port: 8101
    targetPort: 8101
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: cve-tracker-external
  namespace: security-services
spec:
  type: NodePort
  selector:
    app: cve-tracker
  ports:
  - port: 8101
    targetPort: 8101
    nodePort: 30101
    protocol: TCP
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve-tracker
  namespace: security-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cve-tracker
  template:
    metadata:
      labels:
        app: cve-tracker
    spec:
      containers:
      - name: cve-tracker
        image: ghcr.io/quantumlayer-dev/cve-tracker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8101
        env:
        - name: PORT
          value: "8101"
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@postgres-postgresql.temporal.svc.cluster.local:5432/cve_tracker?sslmode=disable"
        - name: NVD_API_KEY
          valueFrom:
            secretKeyRef:
              name: nvd-api-credentials
              key: api-key
              optional: true
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8101
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8101
          initialDelaySeconds: 10
          periodSeconds: 10
      imagePullSecrets:
      - name: ghcr-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: nvd-api-credentials
  namespace: security-services
type: Opaque
data:
  # Base64 encoded API key (empty for now - add real key later)
  api-key: ""

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cve-sync
  namespace: security-services
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cve-sync
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              curl -X POST http://cve-tracker:8101/cve/sync
              echo "CVE sync triggered at $(date)"
          restartPolicy: OnFailure

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cve-tracker-config
  namespace: security-services
data:
  severity-levels: |
    critical: 9.0-10.0
    high: 7.0-8.9
    medium: 4.0-6.9
    low: 0.0-3.9
  
  sources: |
    nvd: https://services.nvd.nist.gov/rest/json/cves/2.0
    mitre: https://cve.mitre.org/data/downloads
    github: https://api.github.com/security-advisories
    
  sync-config: |
    interval: 6h
    batch_size: 100
    max_retries: 3
    timeout: 30s