apiVersion: v1
kind: Secret
metadata:
  name: llm-api-keys
  namespace: quantumlayer
type: Opaque
stringData:
  # Replace these with actual API keys
  OPENAI_API_KEY: "sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  ANTHROPIC_API_KEY: "sk-ant-api03-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  GROQ_API_KEY: "gsk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  BEDROCK_ACCESS_KEY: "AKIAIOSFODNN7EXAMPLE"
  BEDROCK_SECRET_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  BEDROCK_REGION: "us-east-1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-router-config
  namespace: quantumlayer
data:
  config.yaml: |
    server:
      port: 8080
      metrics_port: 9090
      health_port: 8081
      
    providers:
      openai:
        enabled: true
        endpoint: https://api.openai.com/v1
        timeout: 30s
        rateLimit: 100
        tokenBucket: 100000
        models:
          - gpt-4-turbo-preview
          - gpt-4
          - gpt-3.5-turbo
      
      anthropic:
        enabled: true
        endpoint: https://api.anthropic.com
        timeout: 30s
        rateLimit: 50
        tokenBucket: 50000
        models:
          - claude-3-opus-20240229
          - claude-3-sonnet-20240229
          - claude-3-haiku-20240307
      
      groq:
        enabled: true
        endpoint: https://api.groq.com/openai/v1
        timeout: 20s
        rateLimit: 30
        tokenBucket: 30000
        models:
          - mixtral-8x7b-32768
          - llama2-70b-4096
      
      bedrock:
        enabled: false
        region: us-east-1
        timeout: 30s
        rateLimit: 50
        tokenBucket: 50000
        models:
          - anthropic.claude-v2
          - amazon.titan-text-express-v1
    
    routing:
      strategy: "cost-optimized"  # Options: round-robin, least-latency, cost-optimized, priority
      fallback: true
      retries: 3
      circuitBreaker:
        enabled: true
        maxFailures: 5
        resetTimeout: 60s
      
    cache:
      enabled: true
      ttl: 3600
      maxSize: 1000
      
    security:
      apiKeyHeader: "X-API-Key"
      rateLimitPerKey: 1000
      
    observability:
      tracing:
        enabled: true
        jaegerEndpoint: "jaeger-collector.istio-system.svc.cluster.local:14268"
      metrics:
        enabled: true
        prometheusPath: "/metrics"
      logging:
        level: "info"
        format: "json"