apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-gateway
  namespace: quantumlayer
  labels:
    app: mcp-gateway
    component: integration
    tier: platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mcp-gateway
  template:
    metadata:
      labels:
        app: mcp-gateway
        component: integration
        tier: platform
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: mcp-gateway
        image: ghcr.io/quantumlayer-dev/mcp-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8095
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: PORT
          value: "8095"
        - name: ENVIRONMENT
          value: "production"
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: mcp-credentials
              key: github-token
              optional: true
        - name: JIRA_TOKEN
          valueFrom:
            secretKeyRef:
              name: mcp-credentials
              key: jira-token
              optional: true
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: mcp-credentials
              key: slack-token
              optional: true
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8095
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8095
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-gateway
  namespace: quantumlayer
  labels:
    app: mcp-gateway
    component: integration
spec:
  type: NodePort
  selector:
    app: mcp-gateway
  ports:
  - port: 80
    targetPort: 8095
    nodePort: 30895
    name: http
  - port: 9090
    targetPort: 9090
    nodePort: 30995
    name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-gateway-internal
  namespace: quantumlayer
  labels:
    app: mcp-gateway
    component: integration
spec:
  type: ClusterIP
  selector:
    app: mcp-gateway
  ports:
  - port: 80
    targetPort: 8095
    name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mcp-gateway-hpa
  namespace: quantumlayer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mcp-gateway
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80