apiVersion: v1
kind: ConfigMap
metadata:
  name: meta-prompt-engine-config
  namespace: quantumlayer
data:
  PORT: "8080"
  LOG_LEVEL: "info"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-rw"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "quantumlayer"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector.istio-system:4317"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: meta-prompt-engine-secrets
  namespace: quantumlayer
type: Opaque
stringData:
  POSTGRES_USER: "qlayer"
  POSTGRES_PASSWORD: "QuantumLayer2024!"
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-prompt-engine
  namespace: quantumlayer
  labels:
    app: meta-prompt-engine
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meta-prompt-engine
  template:
    metadata:
      labels:
        app: meta-prompt-engine
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: meta-prompt-engine
      containers:
      - name: meta-prompt-engine
        image: ghcr.io/quantumlayer-dev/meta-prompt-engine:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SERVICE_NAME
          value: "meta-prompt-engine"
        - name: ENVIRONMENT
          value: "production"
        envFrom:
        - configMapRef:
            name: meta-prompt-engine-config
        - secretRef:
            name: meta-prompt-engine-secrets
        - secretRef:
            name: llm-credentials
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: templates
          mountPath: /app/templates
          readOnly: true
      volumes:
      - name: templates
        configMap:
          name: prompt-templates
          optional: true
          
---
apiVersion: v1
kind: Service
metadata:
  name: meta-prompt-engine
  namespace: quantumlayer
  labels:
    app: meta-prompt-engine
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: meta-prompt-engine
    
---
apiVersion: v1
kind: Service
metadata:
  name: meta-prompt-engine-nodeport
  namespace: quantumlayer
  labels:
    app: meta-prompt-engine
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30885
    protocol: TCP
    name: http
  selector:
    app: meta-prompt-engine
    
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: meta-prompt-engine-hpa
  namespace: quantumlayer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meta-prompt-engine
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
        
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: meta-prompt-engine-pdb
  namespace: quantumlayer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: meta-prompt-engine
      
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meta-prompt-engine
  namespace: quantumlayer
  labels:
    app: meta-prompt-engine
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: meta-prompt-engine
  namespace: quantumlayer
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: meta-prompt-engine
  namespace: quantumlayer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: meta-prompt-engine
subjects:
- kind: ServiceAccount
  name: meta-prompt-engine
  namespace: quantumlayer
  
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: meta-prompt-engine
  namespace: quantumlayer
spec:
  hosts:
  - meta-prompt-engine
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: meta-prompt-engine
        port:
          number: 80
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
      
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: meta-prompt-engine
  namespace: quantumlayer
spec:
  host: meta-prompt-engine
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        http2MaxRequests: 100
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 30s