apiVersion: v1
kind: ConfigMap
metadata:
  name: parser-config
  namespace: quantumlayer
data:
  PORT: "8082"
  LOG_LEVEL: "info"
  MAX_FILE_SIZE: "10485760"  # 10MB
  CACHE_TTL: "3600"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
  namespace: quantumlayer
  labels:
    app: parser
    component: core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
        component: core
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: parser
        image: ghcr.io/quantumlayer-dev/parser:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: http
        envFrom:
        - configMapRef:
            name: parser-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: parser
  namespace: quantumlayer
  labels:
    app: parser
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: parser
---
apiVersion: v1
kind: Service
metadata:
  name: parser-nodeport
  namespace: quantumlayer
  labels:
    app: parser
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30882
    protocol: TCP
    name: http
  selector:
    app: parser