apiVersion: v1
kind: Service
metadata:
  name: qinfra-ai
  namespace: quantumlayer
spec:
  type: ClusterIP
  selector:
    app: qinfra-ai
  ports:
  - port: 8098
    targetPort: 8098
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: qinfra-ai-external
  namespace: quantumlayer
spec:
  type: NodePort
  selector:
    app: qinfra-ai
  ports:
  - port: 8098
    targetPort: 8098
    nodePort: 30098
    protocol: TCP
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qinfra-ai
  namespace: quantumlayer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qinfra-ai
  template:
    metadata:
      labels:
        app: qinfra-ai
    spec:
      containers:
      - name: qinfra-ai
        image: ghcr.io/quantumlayer-dev/qinfra-ai:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8098
        env:
        - name: PORT
          value: "8098"
        - name: AI_DECISION_ENGINE_URL
          value: "http://ai-decision-engine.quantumlayer.svc.cluster.local:8091"
        - name: LLM_ROUTER_URL
          value: "http://llm-router.quantumlayer.svc.cluster.local:8089"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8098
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8098
          initialDelaySeconds: 10
          periodSeconds: 10
      imagePullSecrets:
      - name: ghcr-secret