# Standalone Temporal UI without Istio sidecar
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui-standalone
  namespace: quantumlayer
  labels:
    app: temporal-ui-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui-standalone
  template:
    metadata:
      labels:
        app: temporal-ui-standalone
      annotations:
        sidecar.istio.io/inject: "false"  # Disable Istio sidecar
    spec:
      containers:
      - name: temporal-ui
        image: temporalio/ui:2.21.3
        env:
        - name: TEMPORAL_ADDRESS
          value: temporal-frontend.quantumlayer.svc.cluster.local:7233
        - name: TEMPORAL_CORS_ORIGINS
          value: "*"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui-standalone
  namespace: quantumlayer
  labels:
    app: temporal-ui-standalone
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30890
    protocol: TCP
    name: http
  selector:
    app: temporal-ui-standalone