apiVersion: v1
kind: Namespace
metadata:
  name: trivy-system

---
apiVersion: v1
kind: Service
metadata:
  name: trivy
  namespace: trivy-system
spec:
  type: ClusterIP
  selector:
    app: trivy
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: trivy-external
  namespace: trivy-system
spec:
  type: NodePort
  selector:
    app: trivy
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30097
    protocol: TCP
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy
  namespace: trivy-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy
  template:
    metadata:
      labels:
        app: trivy
    spec:
      containers:
      - name: trivy
        image: aquasec/trivy:0.48.0
        command:
        - trivy
        - server
        - --listen
        - 0.0.0.0:8080
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: TRIVY_CACHE_DIR
          value: /var/cache/trivy
        - name: TRIVY_DB_REPOSITORY
          value: ghcr.io/aquasecurity/trivy-db
        - name: TRIVY_JAVA_DB_REPOSITORY
          value: ghcr.io/aquasecurity/trivy-java-db
        - name: TRIVY_DEBUG
          value: "false"
        - name: TRIVY_SKIP_UPDATE
          value: "false"
        volumeMounts:
        - name: cache
          mountPath: /var/cache/trivy
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: cache
        emptyDir:
          sizeLimit: 5Gi

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-db-updater
  namespace: trivy-system
spec:
  schedule: "0 */6 * * *"  # Update every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trivy-updater
            image: aquasec/trivy:0.48.0
            command:
            - sh
            - -c
            - |
              trivy image --download-db-only
              trivy image --download-java-db-only
            volumeMounts:
            - name: cache
              mountPath: /var/cache/trivy
            resources:
              requests:
                memory: "128Mi"
                cpu: "50m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          restartPolicy: OnFailure
          volumes:
          - name: cache
            emptyDir:
              sizeLimit: 5Gi