apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-api
  namespace: temporal
  labels:
    app: workflow-api
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workflow-api
  template:
    metadata:
      labels:
        app: workflow-api
        component: api
    spec:
      containers:
      - name: api
        image: ghcr.io/quantumlayer-dev/workflow-api:latest
        imagePullPolicy: Always
        env:
        - name: TEMPORAL_HOST
          value: "temporal-frontend:7233"
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-api
  namespace: temporal
  labels:
    app: workflow-api
spec:
  type: NodePort
  selector:
    app: workflow-api
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30889
    name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: workflow-api
  namespace: temporal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workflow-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80