# Simplified Temporal configuration for QuantumLayer
cassandra:
  enabled: false
mysql:
  enabled: false
elasticsearch:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false

postgresql:
  enabled: true
  auth:
    username: temporal
    password: temporal
    database: temporal

server:
  replicaCount: 1
  config:
    persistence:
      defaultStore: default
      visibilityStore: visibility
      datastores:
        default:
          sql:
            driver: "postgres12"
            host: "temporal-postgresql"
            port: 5432
            database: temporal
            user: temporal
            password: temporal
        visibility:
          sql:
            driver: "postgres12"
            host: "temporal-postgresql"
            port: 5432
            database: temporal_visibility
            user: temporal
            password: temporal

web:
  enabled: true
  service:
    type: NodePort
    nodePort: 30888

admintools:
  enabled: true

schema:
  setup:
    enabled: true
  update:
    enabled: true