# Temporal Helm Chart Values for QuantumLayer V2
# Production configuration with external PostgreSQL

# Disable included datastores
cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: false

elasticsearch:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

# Server configuration
server:
  replicaCount: 1
  
  config:
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres"
          host: "postgres-cluster-rw.quantumlayer.svc.cluster.local"
          port: 5432
          database: "temporal"
          user: "qlayer"
          password: "QuantumLayer2024!"
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"
      
      visibility:
        driver: "sql"
        sql:
          driver: "postgres"
          host: "postgres-cluster-rw.quantumlayer.svc.cluster.local"
          port: 5432
          database: "temporal_visibility"
          user: "qlayer"
          password: "QuantumLayer2024!"
          maxConns: 10
          maxIdleConns: 10
          maxConnLifetime: "1h"
  
  frontend:
    replicaCount: 2
    service:
      type: ClusterIP
      port: 7233
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    podAnnotations:
      sidecar.istio.io/inject: "true"
  
  history:
    replicaCount: 2
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    podAnnotations:
      sidecar.istio.io/inject: "true"
  
  matching:
    replicaCount: 2
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    podAnnotations:
      sidecar.istio.io/inject: "true"
  
  worker:
    replicaCount: 2
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    podAnnotations:
      sidecar.istio.io/inject: "true"

# Web UI
web:
  enabled: true
  replicaCount: 1
  service:
    type: NodePort
    port: 8080
    nodePort: 30888
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Admin tools
admintools:
  enabled: true
  image:
    repository: temporalio/admin-tools
    tag: "1.22.4"

# Schema management
schema:
  setup:
    enabled: true
    backoffLimit: 100
  update:
    enabled: true
    backoffLimit: 100