# Temporal Production Configuration for QuantumLayer
server:
  replicaCount: 1
  config:
    persistence:
      defaultStore: default
      visibilityStore: visibility
      numHistoryShards: 4
      default:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: "postgres-cluster-rw.quantumlayer.svc.cluster.local"
          port: 5432
          database: temporal
          user: qlayer
          password: QuantumLayer2024!
          maxConns: 20
          maxConnLifetime: "1h"
      visibility:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: "postgres-cluster-rw.quantumlayer.svc.cluster.local"
          port: 5432
          database: temporal_visibility
          user: qlayer
          password: QuantumLayer2024!
          maxConns: 10
          maxConnLifetime: "1h"

# Component configurations
frontend:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 7233

history:
  replicaCount: 1

matching:
  replicaCount: 1

worker:
  replicaCount: 1

# Disable datastores we don't need
cassandra:
  enabled: false
  config:
    cluster:
      enabled: false

elasticsearch:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

# Web UI configuration
web:
  enabled: true
  replicaCount: 1
  service:
    type: NodePort
    port: 8080
    nodePort: 30888

# Admin tools
admintools:
  enabled: true
  image:
    repository: temporalio/admin-tools
    tag: 1.24.2

# Schema management
schema:
  setup:
    enabled: true
    backoffLimit: 100
  update:
    enabled: true
    backoffLimit: 100

# Add this to work around the cassandra config requirement
cassandra:
  enabled: false
  hosts:
    - "unused"  # Dummy value to satisfy validation