# Temporal Helm Values - Fixed for latest chart version
server:
  replicaCount: 1
  config:
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: "postgres-cluster-rw.quantumlayer.svc.cluster.local"
          port: 5432
          database: temporal
          user: qlayer
          password: QuantumLayer2024!
          maxConns: 20
          maxConnLifetime: "1h"
      visibility:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: "postgres-cluster-rw.quantumlayer.svc.cluster.local"
          port: 5432
          database: temporal_visibility
          user: qlayer
          password: QuantumLayer2024!
          maxConns: 10
          maxConnLifetime: "1h"

# Disable internal datastores
cassandra:
  enabled: false

elasticsearch:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

# Web UI
web:
  enabled: true
  service:
    type: NodePort
    nodePort: 30888

# Admin tools for schema management
admintools:
  enabled: true

# Schema setup
schema:
  setup:
    enabled: true
  update:
    enabled: true